name: 215a
channels:
  - defaults
dependencies:
  - python
  - pip:
    - numpy
    - pandas
    - geopandas
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyterlab
    - pyreadr
    - joblib
    - cython
    - numba
